// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ConsenSys/fc-latency-map/manager/probes (interfaces: ProbeService)

// Package probes is a generated GoMock package.
package probes

import (
	reflect "reflect"

	models "github.com/ConsenSys/fc-latency-map/manager/models"
	gomock "github.com/golang/mock/gomock"
)

// MockProbeService is a mock of ProbeService interface.
type MockProbeService struct {
	ctrl     *gomock.Controller
	recorder *MockProbeServiceMockRecorder
}

// MockProbeServiceMockRecorder is the mock recorder for MockProbeService.
type MockProbeServiceMockRecorder struct {
	mock *MockProbeService
}

// NewMockProbeService creates a new mock instance.
func NewMockProbeService(ctrl *gomock.Controller) *MockProbeService {
	mock := &MockProbeService{ctrl: ctrl}
	mock.recorder = &MockProbeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProbeService) EXPECT() *MockProbeServiceMockRecorder {
	return m.recorder
}

// GetAllProbes mocks base method.
func (m *MockProbeService) GetAllProbes() []*models.Probe {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProbes")
	ret0, _ := ret[0].([]*models.Probe)
	return ret0
}

// GetAllProbes indicates an expected call of GetAllProbes.
func (mr *MockProbeServiceMockRecorder) GetAllProbes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProbes", reflect.TypeOf((*MockProbeService)(nil).GetAllProbes))
}

// RequestProbes mocks base method.
func (m *MockProbeService) RequestProbes() ([]*models.Probe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestProbes")
	ret0, _ := ret[0].([]*models.Probe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestProbes indicates an expected call of RequestProbes.
func (mr *MockProbeServiceMockRecorder) RequestProbes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestProbes", reflect.TypeOf((*MockProbeService)(nil).RequestProbes))
}

// Update mocks base method.
func (m *MockProbeService) Update() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update")
}

// Update indicates an expected call of Update.
func (mr *MockProbeServiceMockRecorder) Update() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProbeService)(nil).Update))
}
