// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Metrics metrics
//
// swagger:model Metrics
type Metrics struct {

	// locations
	// Required: true
	Locations *int64 `json:"locations"`

	// miners
	// Required: true
	Miners *int64 `json:"miners"`

	// probes
	// Required: true
	Probes *int64 `json:"probes"`
}

// Validate validates this metrics
func (m *Metrics) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMiners(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProbes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Metrics) validateLocations(formats strfmt.Registry) error {

	if err := validate.Required("locations", "body", m.Locations); err != nil {
		return err
	}

	return nil
}

func (m *Metrics) validateMiners(formats strfmt.Registry) error {

	if err := validate.Required("miners", "body", m.Miners); err != nil {
		return err
	}

	return nil
}

func (m *Metrics) validateProbes(formats strfmt.Registry) error {

	if err := validate.Required("probes", "body", m.Probes); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this metrics based on context it is used
func (m *Metrics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Metrics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Metrics) UnmarshalBinary(b []byte) error {
	var res Metrics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
