codecov:
  token: 269e54ad-1d13-4ead-b18c-d2896b275d90
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 29...90

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: true
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "**/mocks.go"