codecov:
  token: 269e54ad-1d13-4ead-b18c-d2896b275d90
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
github_checks:
  annotations: true
coverage:
  status:
    patch:
      default:
        target: '80'
    project:
      default:
        target: '60'
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no
comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  show_carryforward_flags: true
ignore:
  - "**/mocks.go"