version: "3.8"

services:
  manager:
    image: fc-latency-manager
    container_name: fc-latency-manager
    network_mode: "bridge"
    ports:
      - 3001:3000
    volumes:
      - ./manager/data/database.db:/data/database.db
      - ./manager/data/exports:/data/exports
    env_file:
      - ./manager/.env
    restart: unless-stopped
  
  map:
    image: fc-latency-map
    container_name: fc-latency-map
    network_mode: "bridge"
    ports:
      - 3000:3000
    volumes:
      - ./manager/data/exports:/data
    env_file:
      - ./map/.env
    restart: unless-stopped
