version: "3.8"

services:
  manager:
    user: "${FC_UID}:${FC_GID}"
    image: fc-latency-manager
    container_name: fc-latency-manager
    network_mode: "bridge"
    ports:
      - 3001:3000
    volumes:
      - ./exports:/data/exports
    env_file:
      - ./manager/.env
    restart: unless-stopped

  map:
    image: fc-latency-map
    container_name: fc-latency-map
    network_mode: "bridge"
    ports:
      - 3000:3000
    volumes:
      - ./exports:/opt/app/data
    env_file:
      - ./map/.env
    environment:
      - PATH_EXPORTS_MEASURES=/opt/app/data/
    restart: unless-stopped
