linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 55
    statements: 26
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  goimports:
    local-prefixes: github.com/ConsenSys/fc-latency-map
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
  lll:
    line-length: 160
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  nestif:
    min-complexity: 4
  godox:
     keywords:
      - TODO
      - BUG
      - FIXME
      - OPTIMIZE
      - HACK
  gocognit:
    min-complexity: 13
  gocyclo:
    min-complexity: 15
  staticcheck:
    go: "1.17"
    checks: ["all"]
  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.15"
    # https://staticcheck.io/docs/options#checks
    checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]
    # https://staticcheck.io/docs/options#dot_import_whitelist
    dot-import-whitelist:
      - fmt
    # https://staticcheck.io/docs/options#initialisms
    initialisms: [ "ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS" ]
    # https://staticcheck.io/docs/options#http_status_code_whitelist
    http-status-code-whitelist: [ "200", "400", "404", "500" ]
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: unexported-return
      - name: var-declaration
      - name: time-naming
      - name: useless-break
      - name: var-naming
      - name: indent-error-flow
      - name: bool-literal-in-expr
      - name: bare-return
      - name: blank-imports
      - name: unnecessary-stmt
      - name: confusing-results
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: early-return
      - name: duplicated-imports
      - name: constant-logical-expr
      - name: if-return
      - name: increment-decrement
      - name: import-shadowing
      - name: identical-branches
      - name: indent-error-flow
      - name: get-return
      - name: unused-parameter
      - name: unreachable-code
      - name: unconditional-recursion
      - name: var-declaration
      - name: var-naming
      - name: unexported-return
      - name: unexported-naming
      - name: time-naming
      - name: superfluous-else
      - name: struct-tag
      - name: string-format
      - name: string-of-int
      - name: nested-structs
      - name: modifies-value-receiver
      - name: modifies-parameter
      - name: function-result-limit
        arguments: 3
      - name: argument-limit
        arguments: 4
      - name: cyclomatic
        arguments: 16
      - name: add-constant
        arguments:
          - maxLitCount: "5"
            allowStrs: '"","error"'
            allowInts: "0,1,2,4,10,32,64,6"
#      - name: exported
#      - name: flag-parameter
#      - name: deep-exit
#      - name: package-comments
#      - name: unused-receiver
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - nestif
    - godox
    - gocognit
    - gocyclo
    - asciicheck
    - importas
    - revive

  # don't enable:
  # - prealloc
  # - revive # see https://github.com/mgechev/revive#available-rules for details.
  # - wsl

run:
  tests: false
  concurrency: 4
