package constants

type Country struct {
	Code string
	Name string
}

var Countries = []Country{
	{Code: "AD", Name: "ANDORRA"},
	{Code: "AE", Name: "UNITED ARAB EMIRATES"},
	{Code: "AF", Name: "AFGHANISTAN"},
	{Code: "AG", Name: "ANTIGUA AND BARBUDA"},
	{Code: "AI", Name: "ANGUILLA"},
	{Code: "AL", Name: "ALBANIA"},
	{Code: "AM", Name: "ARMENIA"},
	{Code: "AO", Name: "ANGOLA"},
	{Code: "AQ", Name: "ANTARCTICA"},
	{Code: "AR", Name: "ARGENTINA"},
	{Code: "AS", Name: "AMERICAN SAMOA"},
	{Code: "AT", Name: "AUSTRIA"},
	{Code: "AU", Name: "AUSTRALIA"},
	{Code: "AW", Name: "ARUBA"},
	{Code: "AX", Name: "ÅLAND ISLANDS"},
	{Code: "AZ", Name: "AZERBAIJAN"},
	{Code: "BA", Name: "BOSNIA AND HERZEGOVINA"},
	{Code: "BB", Name: "BARBADOS"},
	{Code: "BD", Name: "BANGLADESH"},
	{Code: "BE", Name: "BELGIUM"},
	{Code: "BF", Name: "BURKINA FASO"},
	{Code: "BG", Name: "BULGARIA"},
	{Code: "BH", Name: "BAHRAIN"},
	{Code: "BI", Name: "BURUNDI"},
	{Code: "BJ", Name: "BENIN"},
	{Code: "BL", Name: "SAINT BARTHELEMY"},
	{Code: "BM", Name: "BERMUDA"},
	{Code: "BN", Name: "BRUNEI DARUSSALAM"},
	{Code: "BO", Name: "BOLIVIA, PLURINATIONAL STATE OF"},
	{Code: "BQ", Name: "BONAIRE, SINT EUSTATIUS AND SABA"},
	{Code: "BR", Name: "BRAZIL"},
	{Code: "BS", Name: "BAHAMAS"},
	{Code: "BT", Name: "BHUTAN"},
	{Code: "BV", Name: "BOUVET ISLAND"},
	{Code: "BW", Name: "BOTSWANA"},
	{Code: "BY", Name: "BELARUS"},
	{Code: "BZ", Name: "BELIZE"},
	{Code: "CA", Name: "CANADA"},
	{Code: "CC", Name: "COCOS (KEELING) ISLANDS"},
	{Code: "CD", Name: "CONGO, THE DEMOCRATIC REPUBLIC OF THE"},
	{Code: "CF", Name: "CENTRAL AFRICAN REPUBLIC"},
	{Code: "CG", Name: "CONGO"},
	{Code: "CH", Name: "SWITZERLAND"},
	{Code: "CI", Name: "COTE D'IVOIRE"},
	{Code: "CK", Name: "COOK ISLANDS"},
	{Code: "CL", Name: "CHILE"},
	{Code: "CM", Name: "CAMEROON"},
	{Code: "CN", Name: "CHINA"},
	{Code: "CO", Name: "COLOMBIA"},
	{Code: "CR", Name: "COSTA RICA"},
	{Code: "CU", Name: "CUBA"},
	{Code: "CV", Name: "CAPE VERDE"},
	{Code: "CW", Name: "CURACAO"},
	{Code: "CX", Name: "CHRISTMAS ISLAND"},
	{Code: "CY", Name: "CYPRUS"},
	{Code: "CZ", Name: "CZECH REPUBLIC"},
	{Code: "DE", Name: "GERMANY"},
	{Code: "DJ", Name: "DJIBOUTI"},
	{Code: "DK", Name: "DENMARK"},
	{Code: "DM", Name: "DOMINICA"},
	{Code: "DO", Name: "DOMINICAN REPUBLIC"},
	{Code: "DZ", Name: "ALGERIA"},
	{Code: "EC", Name: "ECUADOR"},
	{Code: "EE", Name: "ESTONIA"},
	{Code: "EG", Name: "EGYPT"},
	{Code: "EH", Name: "WESTERN SAHARA"},
	{Code: "ER", Name: "ERITREA"},
	{Code: "ES", Name: "SPAIN"},
	{Code: "ET", Name: "ETHIOPIA"},
	{Code: "FI", Name: "FINLAND"},
	{Code: "FJ", Name: "FIJI"},
	{Code: "FK", Name: "FALKLAND ISLANDS (MALVINAS)"},
	{Code: "FM", Name: "MICRONESIA, FEDERATED STATES OF"},
	{Code: "FO", Name: "FAROE ISLANDS"},
	{Code: "FR", Name: "FRANCE"},
	{Code: "GA", Name: "GABON"},
	{Code: "GB", Name: "UNITED KINGDOM"},
	{Code: "GD", Name: "GRENADA"},
	{Code: "GE", Name: "GEORGIA"},
	{Code: "GF", Name: "FRENCH GUIANA"},
	{Code: "GG", Name: "GUERNSEY"},
	{Code: "GH", Name: "GHANA"},
	{Code: "GI", Name: "GIBRALTAR"},
	{Code: "GL", Name: "GREENLAND"},
	{Code: "GM", Name: "GAMBIA"},
	{Code: "GN", Name: "GUINEA"},
	{Code: "GP", Name: "GUADELOUPE"},
	{Code: "GQ", Name: "EQUATORIAL GUINEA"},
	{Code: "GR", Name: "GREECE"},
	{Code: "GS", Name: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"},
	{Code: "GT", Name: "GUATEMALA"},
	{Code: "GU", Name: "GUAM"},
	{Code: "GW", Name: "GUINEA-BISSAU"},
	{Code: "GY", Name: "GUYANA"},
	{Code: "HK", Name: "HONG KONG"},
	{Code: "HM", Name: "HEARD ISLAND AND MCDONALD ISLANDS"},
	{Code: "HN", Name: "HONDURAS"},
	{Code: "HR", Name: "CROATIA"},
	{Code: "HT", Name: "HAITI"},
	{Code: "HU", Name: "HUNGARY"},
	{Code: "ID", Name: "INDONESIA"},
	{Code: "IE", Name: "IRELAND"},
	{Code: "IL", Name: "ISRAEL"},
	{Code: "IM", Name: "ISLE OF MAN"},
	{Code: "IN", Name: "INDIA"},
	{Code: "IO", Name: "BRITISH INDIAN OCEAN TERRITORY"},
	{Code: "IQ", Name: "IRAQ"},
	{Code: "IR", Name: "IRAN, ISLAMIC REPUBLIC OF"},
	{Code: "IS", Name: "ICELAND"},
	{Code: "IT", Name: "ITALY"},
	{Code: "JE", Name: "JERSEY"},
	{Code: "JM", Name: "JAMAICA"},
	{Code: "JO", Name: "JORDAN"},
	{Code: "JP", Name: "JAPAN"},
	{Code: "KE", Name: "KENYA"},
	{Code: "KG", Name: "KYRGYZSTAN"},
	{Code: "KH", Name: "CAMBODIA"},
	{Code: "KI", Name: "KIRIBATI"},
	{Code: "KM", Name: "COMOROS"},
	{Code: "KN", Name: "SAINT KITTS AND NEVIS"},
	{Code: "KP", Name: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"},
	{Code: "KR", Name: "KOREA, REPUBLIC OF"},
	{Code: "KW", Name: "KUWAIT"},
	{Code: "KY", Name: "CAYMAN ISLANDS"},
	{Code: "KZ", Name: "KAZAKHSTAN"},
	{Code: "LA", Name: "LAO PEOPLE'S DEMOCRATIC REPUBLIC"},
	{Code: "LB", Name: "LEBANON"},
	{Code: "LC", Name: "SAINT LUCIA"},
	{Code: "LI", Name: "LIECHTENSTEIN"},
	{Code: "LK", Name: "SRI LANKA"},
	{Code: "LR", Name: "LIBERIA"},
	{Code: "LS", Name: "LESOTHO"},
	{Code: "LT", Name: "LITHUANIA"},
	{Code: "LU", Name: "LUXEMBOURG"},
	{Code: "LV", Name: "LATVIA"},
	{Code: "LY", Name: "LIBYA"},
	{Code: "MA", Name: "MOROCCO"},
	{Code: "MC", Name: "MONACO"},
	{Code: "MD", Name: "MOLDOVA, REPUBLIC OF"},
	{Code: "ME", Name: "MONTENEGRO"},
	{Code: "MF", Name: "SAINT MARTIN (FRENCH PART)"},
	{Code: "MG", Name: "MADAGASCAR"},
	{Code: "MH", Name: "MARSHALL ISLANDS"},
	{Code: "MK", Name: "NORTH MACEDONIA"},
	{Code: "ML", Name: "MALI"},
	{Code: "MM", Name: "MYANMAR"},
	{Code: "MN", Name: "MONGOLIA"},
	{Code: "MO", Name: "MACAO"},
	{Code: "MP", Name: "NORTHERN MARIANA ISLANDS"},
	{Code: "MQ", Name: "MARTINIQUE"},
	{Code: "MR", Name: "MAURITANIA"},
	{Code: "MS", Name: "MONTSERRAT"},
	{Code: "MT", Name: "MALTA"},
	{Code: "MU", Name: "MAURITIUS"},
	{Code: "MV", Name: "MALDIVES"},
	{Code: "MW", Name: "MALAWI"},
	{Code: "MX", Name: "MEXICO"},
	{Code: "MY", Name: "MALAYSIA"},
	{Code: "MZ", Name: "MOZAMBIQUE"},
	{Code: "NA", Name: "NAMIBIA"},
	{Code: "NC", Name: "NEW CALEDONIA"},
	{Code: "NE", Name: "NIGER"},
	{Code: "NF", Name: "NORFOLK ISLAND"},
	{Code: "NG", Name: "NIGERIA"},
	{Code: "NI", Name: "NICARAGUA"},
	{Code: "NL", Name: "NETHERLANDS"},
	{Code: "NO", Name: "NORWAY"},
	{Code: "NP", Name: "NEPAL"},
	{Code: "NR", Name: "NAURU"},
	{Code: "NU", Name: "NIUE"},
	{Code: "NZ", Name: "NEW ZEALAND"},
	{Code: "OM", Name: "OMAN"},
	{Code: "PA", Name: "PANAMA"},
	{Code: "PE", Name: "PERU"},
	{Code: "PF", Name: "FRENCH POLYNESIA"},
	{Code: "PG", Name: "PAPUA NEW GUINEA"},
	{Code: "PH", Name: "PHILIPPINES"},
	{Code: "PK", Name: "PAKISTAN"},
	{Code: "PL", Name: "POLAND"},
	{Code: "PM", Name: "SAINT PIERRE AND MIQUELON"},
	{Code: "PN", Name: "PITCAIRN"},
	{Code: "PR", Name: "PUERTO RICO"},
	{Code: "PS", Name: "PALESTINE, STATE OF"},
	{Code: "PT", Name: "PORTUGAL"},
	{Code: "PW", Name: "PALAU"},
	{Code: "PY", Name: "PARAGUAY"},
	{Code: "QA", Name: "QATAR"},
	{Code: "RE", Name: "REUNION"},
	{Code: "RO", Name: "ROMANIA"},
	{Code: "RS", Name: "SERBIA"},
	{Code: "RU", Name: "RUSSIAN FEDERATION"},
	{Code: "RW", Name: "RWANDA"},
	{Code: "SA", Name: "SAUDI ARABIA"},
	{Code: "SB", Name: "SOLOMON ISLANDS"},
	{Code: "SC", Name: "SEYCHELLES"},
	{Code: "SD", Name: "SUDAN"},
	{Code: "SE", Name: "SWEDEN"},
	{Code: "SG", Name: "SINGAPORE"},
	{Code: "SH", Name: "SAINT HELENA"},
	{Code: "SI", Name: "SLOVENIA"},
	{Code: "SJ", Name: "SVALBARD AND JAN MAYEN"},
	{Code: "SK", Name: "SLOVAKIA"},
	{Code: "SL", Name: "SIERRA LEONE"},
	{Code: "SM", Name: "SAN MARINO"},
	{Code: "SN", Name: "SENEGAL"},
	{Code: "SO", Name: "SOMALIA"},
	{Code: "SR", Name: "SURIName"},
	{Code: "SS", Name: "SOUTH SUDAN"},
	{Code: "ST", Name: "SAO TOME AND PRINCIPE"},
	{Code: "SV", Name: "EL SALVADOR"},
	{Code: "SX", Name: "SINT MAARTEN (DUTCH PART)"},
	{Code: "SY", Name: "SYRIAN ARAB REPUBLIC"},
	{Code: "SZ", Name: "ESWATINI"},
	{Code: "TC", Name: "TURKS AND CAICOS ISLANDS"},
	{Code: "TD", Name: "CHAD"},
	{Code: "TF", Name: "FRENCH SOUTHERN TERRITORIES"},
	{Code: "TG", Name: "TOGO"},
	{Code: "TH", Name: "THAILAND"},
	{Code: "TJ", Name: "TAJIKISTAN"},
	{Code: "TK", Name: "TOKELAU"},
	{Code: "TL", Name: "TIMOR-LESTE"},
	{Code: "TM", Name: "TURKMENISTAN"},
	{Code: "TN", Name: "TUNISIA"},
	{Code: "TO", Name: "TONGA"},
	{Code: "TR", Name: "TURKEY"},
	{Code: "TT", Name: "TRINIDAD AND TOBAGO"},
	{Code: "TV", Name: "TUVALU"},
	{Code: "TW", Name: "TAIWAN, PROVINCE OF CHINA"},
	{Code: "TZ", Name: "TANZANIA, UNITED REPUBLIC OF"},
	{Code: "UA", Name: "UKRAINE"},
	{Code: "UG", Name: "UGANDA"},
	{Code: "UM", Name: "UNITED STATES MINOR OUTLYING ISLANDS"},
	{Code: "US", Name: "UNITED STATES"},
	{Code: "UY", Name: "URUGUAY"},
	{Code: "UZ", Name: "UZBEKISTAN"},
	{Code: "VA", Name: "HOLY SEE (VATICAN CITY STATE)"},
	{Code: "VC", Name: "SAINT VINCENT AND THE GRENADINES"},
	{Code: "VE", Name: "VENEZUELA, BOLIVARIAN REPUBLIC OF"},
	{Code: "VG", Name: "VIRGIN ISLANDS, BRITISH"},
	{Code: "VI", Name: "VIRGIN ISLANDS, U.S."},
	{Code: "VN", Name: "VIET NAM"},
	{Code: "VU", Name: "VANUATU"},
	{Code: "WF", Name: "WALLIS AND FUTUNA"},
	{Code: "WS", Name: "SAMOA"},
	{Code: "YE", Name: "YEMEN"},
	{Code: "YT", Name: "MAYOTTE"},
	{Code: "ZA", Name: "SOUTH AFRICA"},
	{Code: "ZM", Name: "ZAMBIA"},
	{Code: "ZW", Name: "ZIMBABWE"},
}
