// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ConsenSys/fc-latency-map/manager/export (interfaces: Service)

// Package export is a generated GoMock package.
package export

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// export mocks base method.
func (m *MockService) export(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "export", arg0)
}

// export indicates an expected call of export.
func (mr *MockServiceMockRecorder) export(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "export", reflect.TypeOf((*MockService)(nil).export), arg0)
}

// exportAll mocks base method.
func (m *MockService) exportAll() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "exportAll")
}

// exportAll indicates an expected call of exportAll.
func (mr *MockServiceMockRecorder) exportAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "exportAll", reflect.TypeOf((*MockService)(nil).exportAll))
}
