sequenceDiagram
    Manager->>+Filecoin Node: Get valid deals
    Filecoin Node-->>-Manager: Returns deals list
    Manager->>+Manager: Get miners list from deals

    Manager->>+Database: Store miners