sequenceDiagram
    
    Manager->>+Database: Get probes
    Database-->>-Manager: Returns probes list

    Manager->>+Ripe Atlas: Create measurement
    Ripe Atlas-->>-Manager: Returns measurement ID

    loop Loop
        Manager->>+Ripe Atlas: Check completion
        Ripe Atlas-->>-Manager: Returns completion status
    end

    Manager->>+Ripe Atlas: Get measurement
    Ripe Atlas-->>-Manager: Returns measurement data

    Manager->>+Database: Store measurements

