// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Retrieval Providers and Retrieval Gateways register.\n",
    "title": "Filecoin Retrieval Register",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/health-check": {
      "get": {
        "description": "\u003cb\u003eGet Manager health check success\u003c/b\u003e",
        "tags": [
          "Check"
        ],
        "summary": "Get Manager health check",
        "operationId": "getHealthCheck",
        "responses": {
          "200": {
            "description": "Manager health check sent",
            "schema": {
              "$ref": "#/definitions/HealthCheck"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "description": "\u003cb\u003eGet Manager general and database metrics\u003c/b\u003e",
        "tags": [
          "Check"
        ],
        "summary": "Get Manager metrics",
        "operationId": "getMetrics",
        "responses": {
          "200": {
            "description": "Manager metrics sent",
            "schema": {
              "$ref": "#/definitions/Metrics"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "HealthCheck": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        }
      }
    },
    "Metrics": {
      "type": "object",
      "required": [
        "locations",
        "miners",
        "probes"
      ],
      "properties": {
        "locations": {
          "type": "integer",
          "format": "int32"
        },
        "miners": {
          "type": "integer",
          "format": "int32"
        },
        "probes": {
          "type": "integer",
          "format": "int32"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Retrieval Providers and Retrieval Gateways register.\n",
    "title": "Filecoin Retrieval Register",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/health-check": {
      "get": {
        "description": "\u003cb\u003eGet Manager health check success\u003c/b\u003e",
        "tags": [
          "Check"
        ],
        "summary": "Get Manager health check",
        "operationId": "getHealthCheck",
        "responses": {
          "200": {
            "description": "Manager health check sent",
            "schema": {
              "$ref": "#/definitions/HealthCheck"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "description": "\u003cb\u003eGet Manager general and database metrics\u003c/b\u003e",
        "tags": [
          "Check"
        ],
        "summary": "Get Manager metrics",
        "operationId": "getMetrics",
        "responses": {
          "200": {
            "description": "Manager metrics sent",
            "schema": {
              "$ref": "#/definitions/Metrics"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "HealthCheck": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        }
      }
    },
    "Metrics": {
      "type": "object",
      "required": [
        "locations",
        "miners",
        "probes"
      ],
      "properties": {
        "locations": {
          "type": "integer",
          "format": "int32"
        },
        "miners": {
          "type": "integer",
          "format": "int32"
        },
        "probes": {
          "type": "integer",
          "format": "int32"
        }
      }
    }
  }
}`))
}
