swagger: "2.0"
info:
  title: "Filecoin Retrieval Register"
  version: "0.0.1"
  description: |
    Retrieval Providers and Retrieval Gateways register.
produces:
  - "application/json"
consumes:
  - "application/json"
schemes:
  - "http"

paths:

  # Notification
  /api/notify:
    post:
      tags:
        - "Notification"
      summary: "Send export notification"
      operationId: "sendNotification"
      description: "<b>Send export notification</b>"
      responses:
        200:
          description: "Manager metrics sent"
          schema:
            $ref: "#/definitions/Notification"
        default:
          description: "Internal error"
          schema:
            $ref: "#/definitions/Error"
            
  # Check
  /api/health-check:
    get:
      tags:
        - "Check"
      summary: "Get Manager health check"
      operationId: "getHealthCheck"
      description: "<b>Get Manager health check success</b>"
      responses:
        200:
          description: "Manager health check sent"
          schema:
            $ref: "#/definitions/HealthCheck"
        default:
          description: "Internal error"
          schema:
            $ref: "#/definitions/Error"
  /api/metrics:
    get:
      tags:
        - "Check"
      summary: "Get Manager metrics"
      operationId: "getMetrics"
      description: "<b>Get Manager general and database metrics</b>"
      responses:
        200:
          description: "Manager metrics sent"
          schema:
            $ref: "#/definitions/Metrics"
        default:
          description: "Internal error"
          schema:
            $ref: "#/definitions/Error"
            
definitions:
  
  # Request
  Notification:
    type: "object"
    properties:
      filename:
        type: "string"
      datetime:
        type: "string"
        
        
  # Responses
  HealthCheck:
    type: "object"
    properties:
      success:
        type: "boolean"
        
  Metrics:
    type: "object"
    properties:
      rssMemory:
        type: "integer"
        format: "int32"
      heapMemoryTotal:
        type: "integer"
        format: "int32"
      heapMemoryUsed:
        type: "integer"
        format: "int32"
      externalMemory:
        type: "integer"
        format: "int32"
        
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
    required:
      - "code"
      - "message"
      
