# Get miners
sequenceDiagram
    Manager->>+Filecoin Node: Get valid deals
    Filecoin Node-->>-Manager: Returns deals list
    Manager->>+Manager: Get miners list from deals

    Manager->>+Database: Store miners

# Get locations
sequenceDiagram
    Manager->>+Manager: Parse airports JSON file
    Manager->>+Database: Insert locations list
    
# Get probes
sequenceDiagram
    Manager->>+Database: Request airports
    Database-->>-Manager: Get airports list

    loop for each airport
        loop increase search distance 
            Manager->>+Ripe Atlas: Request probes
            Ripe Atlas-->>-Manager: Returns probes list

            Manager->>+Maxmind.com: Get probes coordinates
            Maxmind.com-->>-Manager: Returns coordinates
            Manager->>+Manager: Compare data to fix bad coordinates
            Manager->>+Database: Store probes
        end
    end

# Get measurements
sequenceDiagram
    Manager->>+Database: Get probes
    Database-->>-Manager: Returns probes list

    Manager->>+Ripe Atlas: Create measurement
    Ripe Atlas-->>-Manager: Returns measurement ID

    loop Loop
        Manager->>+Ripe Atlas: Check completion
        Ripe Atlas-->>-Manager: Returns completion status
        Manager->>+Ripe Atlas: Get measurement
        Ripe Atlas-->>-Manager: Returns measurement data
        Manager->>+Database: Store measurements
    end

# Export measurements
sequenceDiagram
    Manager->>+Database: Get measurements
    Database-->>-Manager: Returns measurements

    Manager->>+Manager: Export measurements