# Get miners
sequenceDiagram
    Manager->>+Filecoin Node: Get valid deals
    Filecoin Node-->>-Manager: Returns deals list
    Manager->>+Manager: Get miners list from deals

    Manager->>+Database: Store miners

# Get locations
sequenceDiagram
    Manager->>+Manager: Parse airports JSON file
    Manager->>+Database: Insert locations list


# Import probes
sequenceDiagram
Manager->>+Ripe Atlas: Request conencted probes
loop for each probe

        Manager->>+Maxmind.com: Get probes IP coordinates
        Maxmind.com-->>-Manager: Returns coordinates

        Manager->>+Manager: Compare data to fix bad coordinates
        Manager->>+Database: Store probes
end


# Update probes
sequenceDiagram
    Manager->>+Database: Request airports
    Database-->>-Manager: Get airports list

    loop for each airport
        Manager->>+Database: Find probes near to the airport

        Manager->>+Database: Store airport probes association
    end

# Create measurements
sequenceDiagram
Manager->>+Database: Get miners
Database-->>-Manager: Returns miners list
loop for each miner
    loop for each airport near
        Manager->>+Database: Get probes
        Database-->>-Manager: Returns probes list
    end

    Manager->>+Ripe Atlas: Create measurement for miner using probes
    Ripe Atlas-->>-Manager: Returns measurement ID
end

# Get measurements
sequenceDiagram
    loop Loop
        Manager->>+Ripe Atlas: Check completion
        Ripe Atlas-->>-Manager: Returns completion status
        Manager->>+Ripe Atlas: Get measurement
        Ripe Atlas-->>-Manager: Returns measurement data
        Manager->>+Database: Store measurements
    end

# Export measurements
sequenceDiagram
    Manager->>+Database: Get measurements
    Database-->>-Manager: Returns measurements

    Manager->>+Manager: Export measurements