name: CI pipeline
on:
  pull_request:
    branches: [main]
env:
  GO_VERSION: 1.17
jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: manager
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout=2m
  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: $GO_VERSION
      - name: Build sources
        run: |
          cd manager/
          go build ./...
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: $GO_VERSION
      - name: Run test and coverage
        run: |
          cd manager/
          go test -v ./...